apiVersion: v1
kind: Service
metadata:
  name: glusterfs 
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs 
subsets:
  - addresses:
      - ip: 209.97.164.37 
    ports:
      - port: 1 
