apiVersion: v1
kind: PersistentVolume
metadata:
  name: v1
  annotations:
    pv.beta.kubernetes.io/gid: "590" 
spec:
  capacity:
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs 
    path: v3 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
